# Generated by Django 5.1.5 on 2025-01-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_cart_is_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_ordered',
        ),
    ]
